[package]
name = "pass_actions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pass_tool = "0.3.1"

[[bin]]
name = "release_new_version"
path = "src/release_new_version.rs"